using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Data;

namespace ChampionManager25.MisMetodos
{
    public class NacionalidadToFlagConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (value is string nacionalidad)
            {
                // Llamamos al método ObtenerCodigoBanderas
                string banderaCodigo = ObtenerCodigoBanderas(nacionalidad);
                if (banderaCodigo != "default")
                {
                    return new Uri($"/Recursos/img/banderas/{banderaCodigo}.png", UriKind.Relative);
                }
            }
            return new Uri("/Recursos/img/banderas/default.png", UriKind.Relative); // Bandera por defecto
        }

        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            return value; // No es necesario en este caso
        }

        public string ObtenerCodigoBanderas(string nacionalidad)
        {
            return nacionalidad switch
            {
                "Afganistán" => "AFG",
                "Albania" => "ALB",
                "Alemania" => "DEU",
                "Andorra" => "AND",
                "Angola" => "AGO",
                "Antigua y Barbuda" => "ATG",
                "Arabia Saudita" => "SAU",
                "Argelia" => "DZA",
                "Argentina" => "ARG",
                "Armenia" => "ARM",
                "Australia" => "AUS",
                "Austria" => "AUT",
                "Azerbaiyán" => "AZE",
                "Bahamas" => "BHS",
                "Bangladesh" => "BGD",
                "Barbados" => "BRB",
                "Baréin" => "BHR",
                "Bélgica" => "BEL",
                "Belice" => "BLZ",
                "Benín" => "BEN",
                "Bielorrusia" => "BLR",
                "Birmania" => "MMR",
                "Bolivia" => "BOL",
                "Bosnia y Herzegovina" => "BIH",
                "Botsuana" => "BWA",
                "Brasil" => "BRA",
                "Brunéi" => "BRN",
                "Bulgaria" => "BGR",
                "Burkina Faso" => "BFA",
                "Burundi" => "BDI",
                "Bután" => "BTN",
                "Cabo Verde" => "CPV",
                "Camboya" => "KHM",
                "Camerún" => "CMR",
                "Canadá" => "CAN",
                "Chad" => "TCD",
                "Chile" => "CHL",
                "China" => "CHN",
                "Chipre" => "CYP",
                "Colombia" => "COL",
                "Comoras" => "COM",
                "Congo (República del)" => "COG",
                "Congo (República Democrática del)" => "COD",
                "Corea del Norte" => "PRK",
                "Corea del Sur" => "KOR",
                "Costa Rica" => "CRI",
                "Costa de Marfil" => "CIV",
                "Croacia" => "HRV",
                "Cuba" => "CUB",
                "Curazao" => "CRZ",
                "Dinamarca" => "DNK",
                "Dominica" => "DMA",
                "Ecuador" => "ECU",
                "Egipto" => "EGY",
                "El Salvador" => "SLV",
                "Emiratos Árabes Unidos" => "ARE",
                "Eritrea" => "ERI",
                "Escocia" => "SCO",
                "Eslovaquia" => "SVK",
                "Eslovenia" => "SVN",
                "España" => "ESP",
                "Estados Unidos" => "USA",
                "Estonia" => "EST",
                "Eswatini" => "SWZ",
                "Etiopía" => "ETH",
                "Fiji" => "FJI",
                "Filipinas" => "PHL",
                "Finlandia" => "FIN",
                "Francia" => "FRA",
                "Gabón" => "GAB",
                "Gales" => "WAL",
                "Gambia" => "GMB",
                "Georgia" => "GEO",
                "Ghana" => "GHA",
                "Granada" => "GRD",
                "Grecia" => "GRC",
                "Guatemala" => "GTM",
                "Guinea" => "GIN",
                "Guinea-Bisáu" => "GNB",
                "Guyana" => "GUY",
                "Haití" => "HTI",
                "Honduras" => "HND",
                "Hungría" => "HUN",
                "India" => "IND",
                "Indonesia" => "IDN",
                "Inglaterra" => "GBR",
                "Irak" => "IRQ",
                "Irán" => "IRN",
                "Irlanda" => "IRL",
                "Irlanda del Norte" => "NIR",
                "Islandia" => "ISL",
                "Islas Feroe" => "FER",
                "Islas Marshall" => "MHL",
                "Islas Salomón" => "SLB",
                "Israel" => "ISR",
                "Italia" => "ITA",
                "Jamaica" => "JAM",
                "Japón" => "JPN",
                "Jordania" => "JOR",
                "Kazajistán" => "KAZ",
                "Kenia" => "KEN",
                "Kirguistán" => "KGZ",
                "Kiribati" => "KIR",
                "Kosovo" => "KOS",
                "Kuwait" => "KWT",
                "Laos" => "LAO",
                "Lesoto" => "LSO",
                "Letonia" => "LVA",
                "Líbano" => "LBN",
                "Liberia" => "LBR",
                "Libia" => "LBY",
                "Liechtenstein" => "LIE",
                "Lituania" => "LTU",
                "Luxemburgo" => "LUX",
                "Macedonia del Norte" => "MKD",
                "Madagascar" => "MDG",
                "Malasia" => "MYS",
                "Malawi" => "MWI",
                "Maldivas" => "MDV",
                "Mali" => "MLI",
                "Malta" => "MLT",
                "Moldavia" => "MDA",
                "Marruecos" => "MAR",
                "Martinica" => "MTN",
                "Mauricio" => "MUS",
                "Mauritania" => "MRT",
                "México" => "MEX",
                "Micronesia" => "FSM",
                "Mónaco" => "MCO",
                "Mongolia" => "MNG",
                "Montenegro" => "MNE",
                "Mozambique" => "MOZ",
                "Namibia" => "NAM",
                "Nauru" => "NRU",
                "Nepal" => "NPL",
                "Nicaragua" => "NIC",
                "Níger" => "NER",
                "Nigeria" => "NGA",
                "Noruega" => "NOR",
                "Nueva Zelanda" => "NZL",
                "Omán" => "OMN",
                "Países Bajos" => "NLD",
                "Pakistán" => "PAK",
                "Palaos" => "PLW",
                "Panamá" => "PAN",
                "Papúa Nueva Guinea" => "PNG",
                "Paraguay" => "PRY",
                "Perú" => "PER",
                "Polonia" => "POL",
                "Portugal" => "PRT",
                "Reino Unido" => "GBR",
                "República Checa" => "CZE",
                "República del Congo" => "COG",
                "República Dominicana" => "DOM",
                "Ruanda" => "RWA",
                "Rumanía" => "ROU",
                "Rusia" => "RUS",
                "Samoa" => "WSM",
                "San Cristóbal y Nieves" => "KNA",
                "San Marino" => "SMR",
                "Santo Tomé y Príncipe" => "STP",
                "Senegal" => "SEN",
                "Serbia" => "SRB",
                "Seychelles" => "SYC",
                "Sierra Leona" => "SLE",
                "Singapur" => "SGP",
                "Siria" => "SYR",
                "Somalia" => "SOM",
                "Sri Lanka" => "LKA",
                "Sudáfrica" => "ZAF",
                "Sudán" => "SDN",
                "Sudán del Sur" => "SSD",
                "Suecia" => "SWE",
                "Suiza" => "CHE",
                "Surinam" => "SUR",
                "Sáhara Occidental" => "ESH",
                "Tailandia" => "THA",
                "Tayikistán" => "TJK",
                "Tanzania" => "TZA",
                "Togo" => "TGO",
                "Tonga" => "TON",
                "Trinidad y Tobago" => "TTO",
                "Túnez" => "TUN",
                "Turkmenistán" => "TKM",
                "Turquía" => "TUR",
                "Tuvalu" => "TUV",
                "Ucrania" => "UKR",
                "Uganda" => "UGA",
                "Uruguay" => "URY",
                "Uzbekistán" => "UZB",
                "Vanuatu" => "VUT",
                "Vaticano" => "VAT",
                "Venezuela" => "VEN",
                "Vietnam" => "VNM",
                "Yemen" => "YEM",
                "Yibuti" => "DJI",
                "Zambia" => "ZMB",
                "Zimbabue" => "ZWE",
                _ => "default"
            };
        }
    }
}
